#---------------------------------#
#      general configuration      #
#---------------------------------#
 
version: 0.7-build-{build}


#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  matrix:
    - SFML_ROOT:      C:\SFML-VS2015
      SFML_VERSION:   master
      GENERATOR:      Visual Studio 14 2015 Win64
      BUILD_TYPE:     Debug
      SHARED_LIBS:    FALSE
      BUILD_TESTS:    TRUE
      BUILD_EXAMPLES: FALSE
      BUILD_FOLDER:   build-VS2015-Win64

    - SFML_ROOT:      C:\SFML-VS2013
      SFML_VERSION:   2.2
      GENERATOR:      Visual Studio 12 2013
      BUILD_TYPE:     Release
      SHARED_LIBS:    TRUE
      BUILD_TESTS:    FALSE
      BUILD_EXAMPLES: TRUE
      BUILD_FOLDER:   build-VS2013-Win32

clone_depth: 3

cache:
  - C:\SFML-VS2013 -> .appveyor.yml
  - C:\SFML-VS2015 -> .appveyor.yml

install:
- IF "%SFML_VERSION%" == "master" (
    git clone --depth 1 https://github.com/SFML/SFML &&
    cd SFML &&
    IF EXIST "%SFML_ROOT%\lib" (
      IF EXIST "%SFML_ROOT%\revision_cache" (
        git rev-parse HEAD > revision &&
        fc revision "%SFML_ROOT%\revision_cache" > nul &&
        IF errorlevel 0 (
          echo Using cached SFML directory &&
          goto skip_sfml_build
        )
      )
      else (
        echo Rebuilding SFML, cached version is out of date
      )
    )
    else (
      echo Rebuilding SFML, no cache available
    ) &&
    cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%SFML_ROOT% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_SHARED_LIBS=%SHARED_LIBS% . &&
    cmake --build . --target install --config %BUILD_TYPE% -- /m &&
    git rev-parse HEAD > "%SFML_ROOT%\revision_cache" &&
    :skip_sfml_build
  )
  ELSE (
    IF NOT EXIST %SFML_ROOT% (
      appveyor DownloadFile https://github.com/SFML/SFML/archive/%SFML_VERSION%.zip -FileName SFML.zip &&
      7z x SFML.zip > nul &&
      move SFML-%SFML_VERSION% %SFML_ROOT% > nul &&
      cd %SFML_ROOT% &&
      mkdir lib &&
      cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%SFML_ROOT% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_SHARED_LIBS=%SHARED_LIBS% . &&
      cmake --build . --target install --config %BUILD_TYPE% -- /m
    )
  )


#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd C:\projects\tgui
  - mkdir %BUILD_FOLDER%
  - cd %BUILD_FOLDER%
  - cmake -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DTGUI_SHARED_LIBS=%SHARED_LIBS% -DTGUI_BUILD_TESTS=%BUILD_TESTS% -DTGUI_BUILD_EXAMPLES=%BUILD_EXAMPLES% -DSFML_ROOT=%SFML_ROOT% ..
  - msbuild tgui.sln /p:Configuration=%BUILD_TYPE% /m
  - cd ..
  - IF %BUILD_TESTS%==TRUE (
      cd %BUILD_FOLDER%\tests\%BUILD_TYPE% &&
      tests.exe
    )


#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/1feed1f155b2a41e6a62
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
