#---------------------------------#
#      general configuration      #
#---------------------------------#
 
version: 0.7-dev.{build}


#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  SFML_VERSION: master

clone_depth: 3

cache:
  - C:\SFML -> appveyor.yml

install:
  - IF NOT EXIST C:\SFML (
      cd C:\ &&
      appveyor DownloadFile https://github.com/SFML/SFML/archive/%SFML_VERSION%.zip -FileName C:\SFML.zip &&
      7z x C:\SFML.zip &&
      move SFML-%SFML_VERSION% SFML &&
      mkdir C:\SFML\lib &&
      mkdir C:\SFML\build-VS2013-Win32 &&
      cd C:\SFML\build-VS2013-Win32 &&
      cmake -G"Visual Studio 12 2013" -DCMAKE_BUILD_TYPE=Debug .. &&
      msbuild SFML.sln /p:Configuration=Debug /m &&
      xcopy lib\Debug lib\ &&
      cd .. &&
      mkdir C:\SFML\build-VS2015-Win64 &&
      cd C:\SFML\build-VS2015-Win64 &&
      cmake -G"Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release .. &&
      msbuild SFML.sln /p:Configuration=Release /m &&
      xcopy lib\Release lib\ &&
      cd ..
    )

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd C:\projects\tgui
  - mkdir build-VS2013-Win32
  - cd build-VS2013-Win32
  - cmake -G"Visual Studio 12 2013" -DCMAKE_BUILD_TYPE=Debug -DSFML_ROOT=C:\SFML\build-VS2013-Win32 -DSFML_INCLUDE_DIR=C:\SFML\include ..
  - msbuild tgui.sln /p:Configuration=Debug /m
  - cd ..
  - mkdir build-VS2015-Win64
  - cd build-VS2015-Win64
  - cmake -G"Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DSFML_ROOT=C:\SFML\build-VS2015-Win64 -DSFML_INCLUDE_DIR=C:\SFML\include ..
  - msbuild tgui.sln /p:Configuration=Release /m
  - cd ..
